# Generated by Django 6.0.6 on 2026-07-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('home_whitening', 'Teeth Whitening Service at Home - $115'), ('clinic_whitening', 'Teeth Whitening Service at Dental Clinic - $100'), ('ceramic_crown', 'Ceramic Crowns and Fillings - $99'), ('remove_bridge', 'Remove Crowns & Bridges - $50'), ('gum_recession', 'Covering Gum Recession - $400'), ('consultation', 'Consultation - $35'), ('remove_inlay', 'Removal of Old Inlay/Crown - $99'), ('overlay_whitening', 'Overlay Teeth Whitening - $170'), ('implant_crown', 'Implant Crown - $499'), ('implant', 'Dental Implant - $600')], max_length=50)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.CharField(choices=[('09:00', '09:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('01:00', '01:00 PM'), ('02:00', '02:00 PM'), ('03:00', '03:00 PM'), ('04:00', '04:00 PM'), ('05:00', '05:00 PM')], max_length=5)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('appointment_date', 'appointment_time')},
            },
        ),
    ]
