# Generated by Django 6.0.6 on 2026-07-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.CharField(choices=[('09:00', '09:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('01:00', '01:00 PM'), ('02:00', '02:00 PM'), ('03:00', '03:00 PM'), ('04:00', '04:00 PM'), ('05:00', '05:00 PM'), ('06:00', '06:00 PM'), ('07:00', '07:00 PM'), ('08:00', '08:00 PM')], max_length=5),
        ),
    ]
